/**
 * AMY Patch Database & Factory Presets (Complete 256 ESP32 Firmware Parity)
 * Auto-synchronized with components/synth/src/factory_patches.cpp
 */

const AMY_FACTORY_PATCHES = [
  {
    "id": 0,
    "name": "A11 Brass Set 1",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 0,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 1,
    "name": "A12 Brass Swell",
    "category": "Juno PAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 1,
    "wave_type": 3,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 2500,
    "filter_res": 0.8,
    "amp_attack": 350,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 1000
  },
  {
    "id": 2,
    "name": "A13 Trumpet",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 2,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 3,
    "name": "A14 Flutes",
    "category": "Juno WIND",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 3,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4500,
    "filter_res": 0.9,
    "amp_attack": 40,
    "amp_decay": 500,
    "amp_sustain": 0.85,
    "amp_release": 200
  },
  {
    "id": 4,
    "name": "A15 Moving Strings",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 4,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 5,
    "name": "A16 Brass & Strings",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 5,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 6,
    "name": "A17 Choir",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 6,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 7,
    "name": "A18 Piano I",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 7,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 8,
    "name": "A21 Organ I",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 8,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 9,
    "name": "A22 Organ II",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 9,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 10,
    "name": "A23 Combo Organ",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 10,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 11,
    "name": "A24 Calliope",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 11,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 12,
    "name": "A25 Donald Pluck",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 12,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 13,
    "name": "A26 Celeste (1 oct.",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 13,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 14,
    "name": "A27 Elect. Piano I",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 14,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 15,
    "name": "A28 Elect. Piano II",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 15,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 16,
    "name": "A31 Clock Chimes (1",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 16,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 17,
    "name": "A32 Steel Drums",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 17,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 18,
    "name": "A33 Xylophone",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 18,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 19,
    "name": "A34 Brass III",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 19,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 20,
    "name": "A35 Fanfare",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 20,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 21,
    "name": "A36 String III",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 21,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 22,
    "name": "A37 Pizzicato",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 22,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 23,
    "name": "A38 High Strings",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 23,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 24,
    "name": "A41 Bass clarinet",
    "category": "Juno BASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 24,
    "wave_type": 4,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 1200,
    "filter_res": 2.5,
    "amp_attack": 5,
    "amp_decay": 250,
    "amp_sustain": 0.2,
    "amp_release": 100
  },
  {
    "id": 25,
    "name": "A42 English Horn",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 25,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 26,
    "name": "A43 Brass Ensemble",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 26,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 27,
    "name": "A44 Guitar",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 27,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 28,
    "name": "A45 Koto",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 28,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 29,
    "name": "A46 Dark Pluck",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 29,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 30,
    "name": "A47 Funky I",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 30,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 31,
    "name": "A48 Synth Bass I (u",
    "category": "Juno BASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 31,
    "wave_type": 4,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 1200,
    "filter_res": 2.5,
    "amp_attack": 5,
    "amp_decay": 250,
    "amp_sustain": 0.2,
    "amp_release": 100
  },
  {
    "id": 32,
    "name": "A51 Lead I",
    "category": "Juno SYNTH LEAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 32,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 5000,
    "filter_res": 1.8,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 33,
    "name": "A52 Lead II",
    "category": "Juno SYNTH LEAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 33,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 5000,
    "filter_res": 1.8,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 34,
    "name": "A53 Lead III",
    "category": "Juno SYNTH LEAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 34,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 5000,
    "filter_res": 1.8,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 35,
    "name": "A54 Funky II",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 35,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 36,
    "name": "A55 Synth Bass II",
    "category": "Juno BASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 36,
    "wave_type": 4,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 1200,
    "filter_res": 2.5,
    "amp_attack": 5,
    "amp_decay": 250,
    "amp_sustain": 0.2,
    "amp_release": 100
  },
  {
    "id": 37,
    "name": "A56 Funky III",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 37,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 38,
    "name": "A57 Thud Wah",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 38,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 39,
    "name": "A58 Going Up",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 39,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 40,
    "name": "A61 Piano II",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 40,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 41,
    "name": "A62 Clav",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 41,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 42,
    "name": "A63 Frontier Organ",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 42,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 43,
    "name": "A64 Snare Drum (uni",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 43,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 44,
    "name": "A65 Tom Toms (uniso",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 44,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 45,
    "name": "A66 Timpani (unison",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 45,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 46,
    "name": "A67 Shaker",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 46,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 47,
    "name": "A68 Synth Pad",
    "category": "Juno PAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 47,
    "wave_type": 3,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 2500,
    "filter_res": 0.8,
    "amp_attack": 350,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 1000
  },
  {
    "id": 48,
    "name": "A71 Sweep I",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 48,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 49,
    "name": "A72 Pluck Sweep",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 49,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 50,
    "name": "A73 Repeater",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 50,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 51,
    "name": "A74 Sweep II",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 51,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 52,
    "name": "A75 Pluck Bell",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 52,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 53,
    "name": "A76 Dark Synth Pian",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 53,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 54,
    "name": "A77 Sustainer",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 54,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 55,
    "name": "A78 Wah Release",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 55,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 56,
    "name": "A81 Gong (play low",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 56,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 57,
    "name": "A82 Resonance Funk",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 57,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 58,
    "name": "A83 Drum Booms (1 o",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 58,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 59,
    "name": "A84 Dust Storm",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 59,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 60,
    "name": "A85 Rocket Men",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 60,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 61,
    "name": "A86 Hand Claps",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 61,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 62,
    "name": "A87 FX Sweep",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 62,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 63,
    "name": "A88 Caverns",
    "category": "Juno PAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 63,
    "wave_type": 3,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 2500,
    "filter_res": 0.8,
    "amp_attack": 350,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 1000
  },
  {
    "id": 64,
    "name": "B11 Strings",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 64,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 65,
    "name": "B12 Violin",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 65,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 66,
    "name": "B13 Chorus Vibes",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 66,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 67,
    "name": "B14 Organ 1",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 67,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 68,
    "name": "B15 Harpsichord 1",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 68,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 69,
    "name": "B16 Recorder",
    "category": "Juno WIND",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 69,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4500,
    "filter_res": 0.9,
    "amp_attack": 40,
    "amp_decay": 500,
    "amp_sustain": 0.85,
    "amp_release": 200
  },
  {
    "id": 70,
    "name": "B17 Perc. Pluck",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 70,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 71,
    "name": "B18 Noise Sweep",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 71,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 72,
    "name": "B21 Space Chimes",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 72,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 73,
    "name": "B22 Nylon Guitar",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 73,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 74,
    "name": "B23 Orchestral Pad",
    "category": "Juno PAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 74,
    "wave_type": 3,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 2500,
    "filter_res": 0.8,
    "amp_attack": 350,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 1000
  },
  {
    "id": 75,
    "name": "B24 Bright Pluck",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 75,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 76,
    "name": "B25 Organ Bell",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 76,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 77,
    "name": "B26 Accordion",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 77,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 78,
    "name": "B27 FX Rise 1",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 78,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 79,
    "name": "B28 FX Rise 2",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 79,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 80,
    "name": "B31 Brass",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 80,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 81,
    "name": "B32 Helicopter",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 81,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 82,
    "name": "B33 Lute",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 82,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 83,
    "name": "B34 Chorus Funk",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 83,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 84,
    "name": "B35 Tomita",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 84,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 85,
    "name": "B36 FX Sweep 1",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 85,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 86,
    "name": "B37 Sharp Reed",
    "category": "Juno WIND",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 86,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4500,
    "filter_res": 0.9,
    "amp_attack": 40,
    "amp_decay": 500,
    "amp_sustain": 0.85,
    "amp_release": 200
  },
  {
    "id": 87,
    "name": "B38 Bass Pluck",
    "category": "Juno BASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 87,
    "wave_type": 4,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 1200,
    "filter_res": 2.5,
    "amp_attack": 5,
    "amp_decay": 250,
    "amp_sustain": 0.2,
    "amp_release": 100
  },
  {
    "id": 88,
    "name": "B41 Resonant Rise",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 88,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 89,
    "name": "B42 Harpsichord 2",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 89,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 90,
    "name": "B43 Dark Ensemble",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 90,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 91,
    "name": "B44 Contact Wah",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 91,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 92,
    "name": "B45 Noise Sweep 2",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 92,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 93,
    "name": "B46 Glassy Wah",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 93,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 94,
    "name": "B47 Phase Ensemble",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 94,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 95,
    "name": "B48 Chorused Bell",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 95,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 96,
    "name": "B51 Clav",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 96,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 97,
    "name": "B52 Organ 2",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 97,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 98,
    "name": "B53 Bassoon",
    "category": "Juno BASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 98,
    "wave_type": 4,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 1200,
    "filter_res": 2.5,
    "amp_attack": 5,
    "amp_decay": 250,
    "amp_sustain": 0.2,
    "amp_release": 100
  },
  {
    "id": 99,
    "name": "B54 Auto Release No",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 99,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 100,
    "name": "B55 Brass Ensemble",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 100,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 101,
    "name": "B56 Ethereal",
    "category": "Juno PAD",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 101,
    "wave_type": 3,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 2500,
    "filter_res": 0.8,
    "amp_attack": 350,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 1000
  },
  {
    "id": 102,
    "name": "B57 Chorus Bell 2",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 102,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 103,
    "name": "B58 Blizzard",
    "category": "Juno SYNTH",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 103,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 3500,
    "filter_res": 1.5,
    "amp_attack": 10,
    "amp_decay": 400,
    "amp_sustain": 0.6,
    "amp_release": 250
  },
  {
    "id": 104,
    "name": "B61 E. Piano with T",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 104,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 105,
    "name": "B62 Clarinet",
    "category": "Juno WIND",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 105,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4500,
    "filter_res": 0.9,
    "amp_attack": 40,
    "amp_decay": 500,
    "amp_sustain": 0.85,
    "amp_release": 200
  },
  {
    "id": 106,
    "name": "B63 Thunder",
    "category": "Juno DRUMS/PERC",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 106,
    "wave_type": 7,
    "transpose": 0,
    "voice_count": 4,
    "filter_cutoff": 5000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 350,
    "amp_sustain": 0,
    "amp_release": 150
  },
  {
    "id": 107,
    "name": "B64 Reedy Organ",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 107,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 108,
    "name": "B65 Flute / Horn",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 108,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 109,
    "name": "B66 Toy Rhodes",
    "category": "Juno KEYS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 109,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 2,
    "amp_decay": 1200,
    "amp_sustain": 0.3,
    "amp_release": 250
  },
  {
    "id": 110,
    "name": "B67 Surf's Up",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 110,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 111,
    "name": "B68 OW Bass",
    "category": "Juno BASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 111,
    "wave_type": 4,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 1200,
    "filter_res": 2.5,
    "amp_attack": 5,
    "amp_decay": 250,
    "amp_sustain": 0.2,
    "amp_release": 100
  },
  {
    "id": 112,
    "name": "B71 Piccolo",
    "category": "Juno WIND",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 112,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4500,
    "filter_res": 0.9,
    "amp_attack": 40,
    "amp_decay": 500,
    "amp_sustain": 0.85,
    "amp_release": 200
  },
  {
    "id": 113,
    "name": "B72 Melodic Taps",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 113,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 114,
    "name": "B73 Meow Brass",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 114,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 115,
    "name": "B74 Violin (high)",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 115,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 116,
    "name": "B75 High Bells",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 116,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 117,
    "name": "B76 Rolling Wah",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 117,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 118,
    "name": "B77 Ping Bell",
    "category": "Juno PERC/BELL",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 118,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 9000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 1000,
    "amp_sustain": 0.1,
    "amp_release": 400
  },
  {
    "id": 119,
    "name": "B78 Brassy Organ",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 119,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 120,
    "name": "B81 Low Dark String",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 120,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 121,
    "name": "B82 Piccolo Trumpet",
    "category": "Juno BRASS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 121,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 4000,
    "filter_res": 1,
    "amp_attack": 25,
    "amp_decay": 400,
    "amp_sustain": 0.8,
    "amp_release": 250
  },
  {
    "id": 122,
    "name": "B83 Cello",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 122,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 123,
    "name": "B84 High Strings",
    "category": "Juno STRINGS",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 123,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 6000,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 124,
    "name": "B85 Rocket Men",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 124,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 125,
    "name": "B86 Forbidden Plane",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 125,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 126,
    "name": "B87 Froggy",
    "category": "Juno SYNTH FX",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 126,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 3000,
    "filter_res": 2,
    "amp_attack": 100,
    "amp_decay": 1000,
    "amp_sustain": 0.7,
    "amp_release": 800
  },
  {
    "id": 127,
    "name": "B88 Owgan",
    "category": "Juno ORGAN",
    "type": "Juno",
    "author": "ROLAND JUNO",
    "basePatch": 127,
    "wave_type": 1,
    "transpose": 0,
    "voice_count": 10,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 128,
    "name": "DX7 BRASS 1",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 128,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 129,
    "name": "DX7 BRASS 2",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 129,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 130,
    "name": "DX7 BRASS 3",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 130,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 131,
    "name": "DX7 STRINGS 1",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 131,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 132,
    "name": "DX7 STRINGS 2",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 132,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 133,
    "name": "DX7 STRINGS 3",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 133,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 134,
    "name": "DX7 ORCHESTRA",
    "category": "DX7 FM ORCHESTRA",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 134,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 11000,
    "filter_res": 1,
    "amp_attack": 50,
    "amp_decay": 600,
    "amp_sustain": 0.8,
    "amp_release": 500
  },
  {
    "id": 135,
    "name": "DX7 PIANO 1",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 135,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 136,
    "name": "DX7 PIANO 2",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 136,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 137,
    "name": "DX7 PIANO 3",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 137,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 138,
    "name": "DX7 E.PIANO 1",
    "category": "DX7 FM E.PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 138,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1200,
    "amp_sustain": 0.4,
    "amp_release": 350
  },
  {
    "id": 139,
    "name": "DX7 GUITAR 1",
    "category": "DX7 FM GUITAR",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 139,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 800,
    "amp_sustain": 0.2,
    "amp_release": 200
  },
  {
    "id": 140,
    "name": "DX7 GUITAR 2",
    "category": "DX7 FM GUITAR",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 140,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 800,
    "amp_sustain": 0.2,
    "amp_release": 200
  },
  {
    "id": 141,
    "name": "DX7 SYN-LEAD 1",
    "category": "DX7 FM SYNTH",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 141,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 142,
    "name": "DX7 BASS 1",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 142,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 143,
    "name": "DX7 BASS 2",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 143,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 144,
    "name": "DX7 E.ORGAN 1",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 144,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 145,
    "name": "DX7 PIPES 1",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 145,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 146,
    "name": "DX7 HARPSICH 1",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 146,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 147,
    "name": "DX7 CLAV 1",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 147,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 148,
    "name": "DX7 VIBE 1",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 148,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 149,
    "name": "DX7 MARIMBA",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 149,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 150,
    "name": "DX7 KOTO",
    "category": "DX7 FM ETHNIC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 150,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 400,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 151,
    "name": "DX7 FLUTE 1",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 151,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 152,
    "name": "DX7 ORCH-CHIME",
    "category": "DX7 FM ORCHESTRA",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 152,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 11000,
    "filter_res": 1,
    "amp_attack": 50,
    "amp_decay": 600,
    "amp_sustain": 0.8,
    "amp_release": 500
  },
  {
    "id": 153,
    "name": "DX7 TUB BELLS",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 153,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 154,
    "name": "DX7 STEEL DRUM",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 154,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 155,
    "name": "DX7 TIMPANI",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 155,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 156,
    "name": "DX7 REFS WHISL",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 156,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 157,
    "name": "DX7 VOICE 1",
    "category": "DX7 FM VOICE",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 157,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 80,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 400
  },
  {
    "id": 158,
    "name": "DX7 TRAIN",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 158,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 159,
    "name": "DX7 TAKE OFF",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 159,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 160,
    "name": "DX7 PIANO 4",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 160,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 161,
    "name": "DX7 PIANO 5",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 161,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 162,
    "name": "DX7 E.PIANO 2",
    "category": "DX7 FM E.PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 162,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1200,
    "amp_sustain": 0.4,
    "amp_release": 350
  },
  {
    "id": 163,
    "name": "DX7 E.PIANO 3",
    "category": "DX7 FM E.PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 163,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1200,
    "amp_sustain": 0.4,
    "amp_release": 350
  },
  {
    "id": 164,
    "name": "DX7 E.PIANO 4",
    "category": "DX7 FM E.PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 164,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1200,
    "amp_sustain": 0.4,
    "amp_release": 350
  },
  {
    "id": 165,
    "name": "DX7 PIANO 5THS",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 165,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 166,
    "name": "DX7 CELESTE",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 166,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 167,
    "name": "DX7 TOY PIANO",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 167,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 168,
    "name": "DX7 HARPSICH 2",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 168,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 169,
    "name": "DX7 HARPSICH 3",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 169,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 170,
    "name": "DX7 CLAV 2",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 170,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 171,
    "name": "DX7 CLAV 3",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 171,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 172,
    "name": "DX7 E.ORGAN 2",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 172,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 173,
    "name": "DX7 E.ORGAN 3",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 173,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 174,
    "name": "DX7 E.ORGAN 4",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 174,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 175,
    "name": "DX7 E.ORGAN 5",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 175,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 176,
    "name": "DX7 PIPES 2",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 176,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 177,
    "name": "DX7 PIPES 3",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 177,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 178,
    "name": "DX7 PIPES 4",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 178,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 179,
    "name": "DX7 CALIOPE",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 179,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 180,
    "name": "DX7 ACCORDION",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 180,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 181,
    "name": "DX7 SITAR",
    "category": "DX7 FM ETHNIC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 181,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 400,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 182,
    "name": "DX7 GUITAR 3",
    "category": "DX7 FM GUITAR",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 182,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 800,
    "amp_sustain": 0.2,
    "amp_release": 200
  },
  {
    "id": 183,
    "name": "DX7 GUITAR 4",
    "category": "DX7 FM GUITAR",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 183,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 800,
    "amp_sustain": 0.2,
    "amp_release": 200
  },
  {
    "id": 184,
    "name": "DX7 GUITAR 5",
    "category": "DX7 FM GUITAR",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 184,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 800,
    "amp_sustain": 0.2,
    "amp_release": 200
  },
  {
    "id": 185,
    "name": "DX7 GUITAR 6",
    "category": "DX7 FM GUITAR",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 185,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 800,
    "amp_sustain": 0.2,
    "amp_release": 200
  },
  {
    "id": 186,
    "name": "DX7 LUTE",
    "category": "DX7 FM ETHNIC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 186,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 400,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 187,
    "name": "DX7 BANJO",
    "category": "DX7 FM ETHNIC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 187,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 400,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 188,
    "name": "DX7 HARP 1",
    "category": "DX7 FM ETHNIC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 188,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 400,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 189,
    "name": "DX7 HARP 2",
    "category": "DX7 FM ETHNIC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 189,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 1,
    "amp_decay": 400,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 190,
    "name": "DX7 BASS 3",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 190,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 191,
    "name": "DX7 BASS 4",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 191,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 192,
    "name": "DX7 PICCOLO",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 192,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 193,
    "name": "DX7 FLUTE 2",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 193,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 194,
    "name": "DX7 OBOE",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 194,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 195,
    "name": "DX7 CLARINET",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 195,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 196,
    "name": "DX7 SAX BC",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 196,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 197,
    "name": "DX7 BASSOON",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 197,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 198,
    "name": "DX7 STRINGS 4",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 198,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 199,
    "name": "DX7 STRINGS 5",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 199,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 200,
    "name": "DX7 STRINGS 6",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 200,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 201,
    "name": "DX7 STRINGS 7",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 201,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 202,
    "name": "DX7 STRINGS 8",
    "category": "DX7 FM STRINGS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 202,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8500,
    "filter_res": 0.9,
    "amp_attack": 180,
    "amp_decay": 800,
    "amp_sustain": 0.85,
    "amp_release": 600
  },
  {
    "id": 203,
    "name": "DX7 BRASS 4",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 203,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 204,
    "name": "DX7 BRASS 5",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 204,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 205,
    "name": "DX7 BRASS 6 BC",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 205,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 206,
    "name": "DX7 BRASS 7",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 206,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 207,
    "name": "DX7 BRASS 8",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 207,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 208,
    "name": "DX7 RECORDER",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 208,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 209,
    "name": "DX7 HARMONICA1",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 209,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 210,
    "name": "DX7 HRMNCA2 BC",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 210,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 211,
    "name": "DX7 VOICE 2",
    "category": "DX7 FM VOICE",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 211,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 80,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 400
  },
  {
    "id": 212,
    "name": "DX7 VOICE 3",
    "category": "DX7 FM VOICE",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 212,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 80,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 400
  },
  {
    "id": 213,
    "name": "DX7 GLOKENSPL",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 213,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 214,
    "name": "DX7 VIBE 2",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 214,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 215,
    "name": "DX7 XYLOPHONE",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 215,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 216,
    "name": "DX7 CHIMES",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 216,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 217,
    "name": "DX7 GONG 1",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 217,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 218,
    "name": "DX7 GONG 2",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 218,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 219,
    "name": "DX7 BELLS",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 219,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 220,
    "name": "DX7 COW BELL",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 220,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 221,
    "name": "DX7 BLOCK",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 221,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 222,
    "name": "DX7 FLEXATONE",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 222,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 223,
    "name": "DX7 LOG DRUM",
    "category": "DX7 FM PERC",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 223,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 450,
    "amp_sustain": 0,
    "amp_release": 200
  },
  {
    "id": 224,
    "name": "DX7 SYN-LEAD 2",
    "category": "DX7 FM SYNTH",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 224,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 225,
    "name": "DX7 SYN-LEAD 3",
    "category": "DX7 FM SYNTH",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 225,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 226,
    "name": "DX7 SYN-LEAD 4",
    "category": "DX7 FM SYNTH",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 226,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 227,
    "name": "DX7 SYN-LEAD 5",
    "category": "DX7 FM SYNTH",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 227,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 12000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 300,
    "amp_sustain": 0.8,
    "amp_release": 200
  },
  {
    "id": 228,
    "name": "DX7 SYN-CLAV 1",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 228,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 229,
    "name": "DX7 SYN-CLAV 2",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 229,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 230,
    "name": "DX7 SYN-CLAV 3",
    "category": "DX7 FM KEYS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 230,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 9000,
    "filter_res": 1.5,
    "amp_attack": 1,
    "amp_decay": 250,
    "amp_sustain": 0,
    "amp_release": 120
  },
  {
    "id": 231,
    "name": "DX7 SYN-PIANO",
    "category": "DX7 FM PIANO",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 231,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 1500,
    "amp_sustain": 0.3,
    "amp_release": 300
  },
  {
    "id": 232,
    "name": "DX7 SYNBRASS 1",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 232,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 233,
    "name": "DX7 SYNBRASS 2",
    "category": "DX7 FM BRASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 233,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 5,
    "amp_decay": 400,
    "amp_sustain": 0.7,
    "amp_release": 250
  },
  {
    "id": 234,
    "name": "DX7 SYNORGAN 1",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 234,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 235,
    "name": "DX7 SYNORGAN 2",
    "category": "DX7 FM ORGAN",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 235,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 200,
    "amp_sustain": 1,
    "amp_release": 100
  },
  {
    "id": 236,
    "name": "DX7 SYN-VOX",
    "category": "DX7 FM VOICE",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 236,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 80,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 400
  },
  {
    "id": 237,
    "name": "DX7 SYN-ORCH",
    "category": "DX7 FM ORCHESTRA",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 237,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 11000,
    "filter_res": 1,
    "amp_attack": 50,
    "amp_decay": 600,
    "amp_sustain": 0.8,
    "amp_release": 500
  },
  {
    "id": 238,
    "name": "DX7 SYN-BASS 1",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 238,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 239,
    "name": "DX7 SYN-BASS 2",
    "category": "DX7 FM BASS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 239,
    "wave_type": 8,
    "transpose": -12,
    "voice_count": 4,
    "filter_cutoff": 3500,
    "filter_res": 2,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0.1,
    "amp_release": 150
  },
  {
    "id": 240,
    "name": "DX7 HARP-FLUTE",
    "category": "DX7 FM WIND",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 240,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 7000,
    "filter_res": 1,
    "amp_attack": 20,
    "amp_decay": 400,
    "amp_sustain": 0.9,
    "amp_release": 200
  },
  {
    "id": 241,
    "name": "DX7 BELL-FLUTE",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 241,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 242,
    "name": "DX7 E.P-BRS BC",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 242,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 243,
    "name": "DX7 T.BL-EXPA",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 243,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 244,
    "name": "DX7 CHIME-STRG",
    "category": "DX7 FM BELL",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 244,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 14000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 2000,
    "amp_sustain": 0,
    "amp_release": 800
  },
  {
    "id": 245,
    "name": "DX7 B.DRM-SNAR",
    "category": "DX7 FM DRUMS",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 245,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 8000,
    "filter_res": 1,
    "amp_attack": 1,
    "amp_decay": 300,
    "amp_sustain": 0,
    "amp_release": 100
  },
  {
    "id": 246,
    "name": "DX7 SHIMMER",
    "category": "DX7 FM PAD",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 246,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 150,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 800
  },
  {
    "id": 247,
    "name": "DX7 EVOLUTION",
    "category": "DX7 FM PAD",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 247,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1,
    "amp_attack": 150,
    "amp_decay": 800,
    "amp_sustain": 0.9,
    "amp_release": 800
  },
  {
    "id": 248,
    "name": "DX7 WATER GDN",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 248,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 249,
    "name": "DX7 WASP STING",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 249,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 250,
    "name": "DX7 LASER GUN",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 250,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 251,
    "name": "DX7 DESCENT",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 251,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 252,
    "name": "DX7 OCTAVE WAR",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 252,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 253,
    "name": "DX7 GRAND PRIX",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 253,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 254,
    "name": "DX7 ST.HELENS",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 254,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 255,
    "name": "DX7 EXPLOSION",
    "category": "DX7 FM FX",
    "type": "DX7",
    "author": "YAMAHA DX7",
    "basePatch": 255,
    "wave_type": 8,
    "transpose": 0,
    "voice_count": 8,
    "filter_cutoff": 10000,
    "filter_res": 1.2,
    "amp_attack": 50,
    "amp_decay": 800,
    "amp_sustain": 0.5,
    "amp_release": 400
  },
  {
    "id": 256,
    "name": "AMY Additive Piano",
    "category": "Acoustic",
    "type": "Additive",
    "basePatch": 256,
    "wave_type": 0,
    "voice_count": 8
  },
  {
    "id": 384,
    "name": "Standard Drum Kit",
    "category": "Drums (GM)",
    "type": "PCM/GM",
    "basePatch": 384,
    "wave_type": 7,
    "voice_count": 4
  },
  {
    "id": 385,
    "name": "TR-808 Drum Kit",
    "category": "Drums (808)",
    "type": "PCM/GM",
    "basePatch": 385,
    "wave_type": 7,
    "voice_count": 4
  },
  {
    "id": 386,
    "name": "TR-909 Drum Kit",
    "category": "Drums (909)",
    "type": "PCM/GM",
    "basePatch": 386,
    "wave_type": 7,
    "voice_count": 4
  },
  {
    "id": 387,
    "name": "LinnDrum Kit",
    "category": "Drums (Linn)",
    "type": "PCM/GM",
    "basePatch": 387,
    "wave_type": 7,
    "voice_count": 4
  }
];

const DEFAULT_PATCH_TEMPLATE = {
  id: 0,
  name: "Init Patch",
  category: "Lead",
  author: "AMY Studio",
  voice_count: 8,
  engine_patch: 0,
  transpose: 0,
  
  // Oscillator 0 (Main)
  wave_type: 2, // SAW_DOWN (AMY enum 2)
  base_freq: 440.0,
  duty: 0.5,
  feedback: 0.0,
  phase: 0.0,
  portamento_ms: 0,
  
  // Filter
  filter_type: 1, // LPF
  filter_cutoff: 2500.0,
  filter_res: 1.2,
  filter_env_amt: 0.5,
  filter_keytrack: 0.3,
  
  // Envelope 0 (Amp)
  amp_attack: 10.0,
  amp_decay: 200.0,
  amp_sustain: 0.7,
  amp_release: 300.0,
  eg0_type: 0, // Normal
  
  // Envelope 1 (Filter/Mod)
  eg1_attack: 20.0,
  eg1_decay: 250.0,
  eg1_sustain: 0.5,
  eg1_release: 400.0,
  eg1_type: 0,
  
  // Master Effects
  reverb_level: 0.25,
  reverb_size: 0.6,
  reverb_damp: 0.4,
  chorus_level: 0.0,
  chorus_rate: 0.5,
  chorus_depth: 0.5,
  delay_level: 0.0,
  delay_time: 350.0,
  delay_feedback: 0.3,
  eq_low: 0.0,
  eq_mid: 0.0,
  eq_high: 0.0,
  
  // Standard SMK-S3 8-Macros
  macros: [
    { name: "CHAR", val: 50 },
    { name: "BRTE", val: 50 },
    { name: "MOTN", val: 30 },
    { name: "SHPE", val: 50 },
    { name: "ATK",  val: 10 },
    { name: "REL",  val: 30 },
    { name: "SPCE", val: 25 },
    { name: "DRV",  val: 0 }
  ]
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { AMY_FACTORY_PATCHES, DEFAULT_PATCH_TEMPLATE };
}
